### ISSUE TITLE
Error when running main script

### ISSUE THREAD

**Issue by sourcesync** [Stephen-Pa/APU#3] opened 2024-06-10 01:57 UTC
I get the following error after following your README instructions.

It looks like I might need to install some low library support or point to where it exists on this machine (F-1) ?

```
(spalli-projects) gwilliams@fractals-1:~/Projects/stephen_palli/APU/semester2998$ ./svmTestScript.sh 
Info: sources and includes are:
Info: dev_inc_dirs="dev_src/include"
Info: dev_extra_inc_dirs=""
Info: dev_h_files=" dev_src/include/gsi_device_lab_3_dma.h"
Info: dev_src_files="dev_src/gsi_device_lab_3.c dev_src/gsi_device_lab_3_dma.c"
Info: apl_src_files=""
Info: host_inc_dirs=""
Info: host_extra_inc_dirs=""
Info: host_h_files=""
Info: host_src_files="gsi_device_lab_3_app.c"
Info: common_host_dev_h_file="gsi_device_lab_3.h"
Info: build with product="gnu-ccac" hardware_type="leda_g" mode="debug" BUILD_DIR=build/debug
Error: mising arc-elf32-tcf-gcc - the compier for the ARC architecture is not found in PATH - see more details with "make help"
make: *** [/home/gwilliams/Projects/stephen_palli/APU/semester2998/../Common/common.mk:693: check-setup] Error 1
./svmTestScript.sh: line 22: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 22: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 30: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 30: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 38: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 38: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 46: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 46: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 54: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 54: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 62: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 62: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 70: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 70: ./build/debug/gsi_device_lab_3: No such file or directory
Gamma 17489 10 19020

Traceback (most recent call last):
  File "/home/gwilliams/Projects/stephen_palli/APU/semester2998/parseCollectedData.py", line 65, in <module>
    parse_file(input_file, int(sys.argv[2]), sys.argv[3])
  File "/home/gwilliams/Projects/stephen_palli/APU/semester2998/parseCollectedData.py", line 51, in parse_file
    averageDataTransferWithOverhead += float(lines[i+2].replace('\n', ''))
ValueError: could not convert string to float: 'Gamma 12370 10 19020'
./svmTestScript.sh: line 81: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 81: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 89: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 89: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 97: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 97: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 105: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 105: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 113: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 113: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 121: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 121: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 129: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 129: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 137: ./build/debug/gsi_device_lab_3: No such file or directory
./svmTestScript.sh: line 137: ./build/debug/gsi_device_lab_3: No such file or directory
MiniBooNE 32659 48 100000

Traceback (most recent call last):
  File "/home/gwilliams/Projects/stephen_palli/APU/semester2998/parseCollectedData.py", line 65, in <module>
    parse_file(input_file, int(sys.argv[2]), sys.argv[3])
  File "/home/gwilliams/Projects/stephen_palli/APU/semester2998/parseCollectedData.py", line 51, in parse_file
    averageDataTransferWithOverhead += float(lines[i+2].replace('\n', ''))
ValueError: could not convert string to float: 'MiniBooNE 32659 48 32768'
(spalli-projects) gwilliams@fractals-1:~/Projects/stephen_palli/APU/semester2998$ 
```

**Comment by Stephen-Pa** [comment] 2024-06-10 13:10
F-1 should have the correct libraries installed. This error should be caused by the compiler not being linked to the PATH. Paste the following export into your .bashrc and restart the terminal to fix the issue:

export PATH=/opt/gsi/ubuntu_20_04/arc_gnu_2021.09-release_elf32_le_linux_no_sdata/arc-snps-elf/bin:${PATH}

**Comment by sourcesync** [comment] 2024-06-10 15:32
Great.  Just confirming...this is what I should get?

```
Gamma 17489 10 19020

 Average Total Time: 2.30895
 Average Data Transfer with Overhead: 0.00280
 Average Data Transfer Without Overhead: 0.00103
 Average Classification With Overhead: 2.17338
 Average Classification Without Overhead: 2.17279

Gamma 12370 10 19020

 Average Total Time: 2.16223
 Average Data Transfer with Overhead: 0.00258
 Average Data Transfer Without Overhead: 0.00102
 Average Classification With Overhead: 2.03632
 Average Classification Without Overhead: 2.03572

Gamma 8463 10 19020

 Average Total Time: 2.16415
 Average Data Transfer with Overhead: 0.00255
 Average Data Transfer Without Overhead: 0.00102
 Average Classification With Overhead: 2.03633
 Average Classification Without Overhead: 2.03577

Gamma 4298 10 19020

 Average Total Time: 2.11174
 Average Data Transfer with Overhead: 0.00251
 Average Data Transfer Without Overhead: 0.00101
 Average Classification With Overhead: 1.97480
 Average Classification Without Overhead: 1.97423

Gamma 17489 10 14265

 Average Total Time: 1.75567
 Average Data Transfer with Overhead: 0.00279
 Average Data Transfer Without Overhead: 0.00110
 Average Classification With Overhead: 1.62901
 Average Classification Without Overhead: 1.62861

Gamma 17489 10 9510

 Average Total Time: 1.20991
 Average Data Transfer with Overhead: 0.00269
 Average Data Transfer Without Overhead: 0.00102
 Average Classification With Overhead: 1.08640
 Average Classification Without Overhead: 1.08604

Gamma 17489 10 4755

 Average Total Time: 0.66726
 Average Data Transfer with Overhead: 0.00259
 Average Data Transfer Without Overhead: 0.00102
 Average Classification With Overhead: 0.54298
 Average Classification Without Overhead: 0.54281

MiniBooNE 32659 48 100000

 Average Total Time: 17.03080
 Average Data Transfer with Overhead: 0.01348
 Average Data Transfer Without Overhead: 0.00273
 Average Classification With Overhead: 16.89508
 Average Classification Without Overhead: 16.89155

MiniBooNE 32659 48 32768

 Average Total Time: 5.66045
 Average Data Transfer with Overhead: 0.01227
 Average Data Transfer Without Overhead: 0.00273
 Average Classification With Overhead: 5.52473
 Average Classification Without Overhead: 5.52348

MiniBooNE 24499 48 32768

 Average Total Time: 5.66003
 Average Data Transfer with Overhead: 0.01147
 Average Data Transfer Without Overhead: 0.00273
 Average Classification With Overhead: 5.52483
 Average Classification Without Overhead: 5.52352

MiniBooNE 16324 48 32768

 Average Total Time: 5.66280
 Average Data Transfer with Overhead: 0.01352
 Average Data Transfer Without Overhead: 0.00273
 Average Classification With Overhead: 5.52575
 Average Classification Without Overhead: 5.52442

MiniBooNE 8162 48 32768

 Average Total Time: 5.31681
 Average Data Transfer with Overhead: 0.00972
 Average Data Transfer Without Overhead: 0.00273
 Average Classification With Overhead: 5.18358
 Average Classification Without Overhead: 5.18227

MiniBooNE 32659 48 24576

 Average Total Time: 4.29257
 Average Data Transfer with Overhead: 0.01506
 Average Data Transfer Without Overhead: 0.00274
 Average Classification With Overhead: 4.15349
 Average Classification Without Overhead: 4.15243

MiniBooNE 32659 48 16384

 Average Total Time: 2.90152
 Average Data Transfer with Overhead: 0.01540
 Average Data Transfer Without Overhead: 0.00273
 Average Classification With Overhead: 2.76223
 Average Classification Without Overhead: 2.76143

MiniBooNE 32659 48 8192

 Average Total Time: 1.51701
 Average Data Transfer with Overhead: 0.01220
 Average Data Transfer Without Overhead: 0.00272
 Average Classification With Overhead: 1.38165
 Average Classification Without Overhead: 1.38109
```

**Comment by Stephen-Pa** [comment] 2024-06-10 17:21
Looks fairly accurate to my data I collected on the super server. Looks like device execution times remain almost the same (could be fluctuation in this due to the number of samples taken. My data is taken over 100 samples, default in test script is 2). Total execution time is partially based on the system hardware (CPU and RAM) for transferring data around. With the F1 refresh I would say this makes sense. Total time includes the time it takes for the entire code to run minus the time to load svm parameters from text files (APU initialize, transfer data from host to device, transfer data from device to host, device to organize data, device to classify queries). Data transfer with overhead is showing the time it takes to transfer data to the APU and for the APU to organize the data it receives. Data transfer without overhead neglects the transfer of data to the APU and only times how long it takes the APU to organize data. Classification with overhead considers the time it takes to load all queries onto the device and for the APU to classify the queries. Classification without overhead only considers the time it takes the APU to classify the queries. 
```
Gamma 17489 10 19020

 Average Total Time: 2.42683
 Average Data Transfer with Overhead: 0.00299
 Average Data Transfer Without Overhead: 0.00111
 Average Classification With Overhead: 2.17167
 Average Classification Without Overhead: 2.17111

Gamma 12370 10 19020

 Average Total Time: 2.27619
 Average Data Transfer with Overhead: 0.00302
 Average Data Transfer Without Overhead: 0.00112
 Average Classification With Overhead: 2.03588
 Average Classification Without Overhead: 2.03533

Gamma 8463 10 19020

 Average Total Time: 2.26462
 Average Data Transfer with Overhead: 0.00303
 Average Data Transfer Without Overhead: 0.00112
 Average Classification With Overhead: 2.03595
 Average Classification Without Overhead: 2.03539

Gamma 4298 10 19020

 Average Total Time: 2.19016
 Average Data Transfer with Overhead: 0.00299
 Average Data Transfer Without Overhead: 0.00111
 Average Classification With Overhead: 1.97410
 Average Classification Without Overhead: 1.97354

Gamma 17489 10 14265

 Average Total Time: 1.87257
 Average Data Transfer with Overhead: 0.00299
 Average Data Transfer Without Overhead: 0.00111
 Average Classification With Overhead: 1.62977
 Average Classification Without Overhead: 1.62938

Gamma 17489 10 9510

 Average Total Time: 1.31670
 Average Data Transfer with Overhead: 0.00298
 Average Data Transfer Without Overhead: 0.00111
 Average Classification With Overhead: 1.08761
 Average Classification Without Overhead: 1.08725

Gamma 17489 10 4755

 Average Total Time: 0.75962
 Average Data Transfer with Overhead: 0.00298
 Average Data Transfer Without Overhead: 0.00112
 Average Classification With Overhead: 0.54303
 Average Classification Without Overhead: 0.54286
 
 MiniBooNE 32659 48 100000

 Average Total Time: 18.70516
 Average Data Transfer with Overhead: 0.01279
 Average Data Transfer Without Overhead: 0.00284
 Average Classification With Overhead: 16.87207
 Average Classification Without Overhead: 16.86842

MiniBooNE 32659 48 32768

 Average Total Time: 6.51048
 Average Data Transfer with Overhead: 0.01274
 Average Data Transfer Without Overhead: 0.00284
 Average Classification With Overhead: 5.53233
 Average Classification Without Overhead: 5.53104

MiniBooNE 24499 48 32768

 Average Total Time: 6.41387
 Average Data Transfer with Overhead: 0.01201
 Average Data Transfer Without Overhead: 0.00284
 Average Classification With Overhead: 5.53083
 Average Classification Without Overhead: 5.52953

MiniBooNE 16324 48 32768

 Average Total Time: 6.30850
 Average Data Transfer with Overhead: 0.01097
 Average Data Transfer Without Overhead: 0.00283
 Average Classification With Overhead: 5.53025
 Average Classification Without Overhead: 5.52895

MiniBooNE 8162 48 32768

 Average Total Time: 5.85203
 Average Data Transfer with Overhead: 0.01026
 Average Data Transfer Without Overhead: 0.00283
 Average Classification With Overhead: 5.18077
 Average Classification Without Overhead: 5.17947

MiniBooNE 32659 48 24576

 Average Total Time: 5.03185
 Average Data Transfer with Overhead: 0.01273
 Average Data Transfer Without Overhead: 0.00283
 Average Classification With Overhead: 4.14922
 Average Classification Without Overhead: 4.14818

MiniBooNE 32659 48 16384

 Average Total Time: 3.54518
 Average Data Transfer with Overhead: 0.01278
 Average Data Transfer Without Overhead: 0.00284
 Average Classification With Overhead: 2.76642
 Average Classification Without Overhead: 2.76562

MiniBooNE 32659 48 8192

 Average Total Time: 2.06202
 Average Data Transfer with Overhead: 0.01279
 Average Data Transfer Without Overhead: 0.00283
 Average Classification With Overhead: 1.38339
 Average Classification Without Overhead: 1.38284
```

**Comment by sourcesync** [comment] 2024-06-10 19:16
ok thanks!  you can close this issue.

**Closed as completed** 2024-06-10 19:18 UTC
